# ACTION METADATA
# https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions

---
name: gh-release-url
author: '@flex-development'
description: Create a URL for a GitHub release
inputs:
  owner:
    default: ${{ github.repository_owner }}
    description: github repository owner
    required: false
  repo:
    default: ${{ github.event.repository.name }}
    description: github repository name
    required: false
  server:
    default: ${{ github.server_url }}
    description: github server url
    required: false
  tag-prefix:
    description: |
      the prefix to append to the release version when building the release tag component of the url
    required: false
  version:
    description: the release version or tag to create a url for
    required: true
outputs:
  tag:
    description: the release tag the url was created with
    value: ${{ steps.tag.outputs.result }}
  url:
    description: the release url
    value: ${{ steps.url.outputs.result }}
runs:
  using: composite
  steps:
    - id: tag
      shell: bash
      run: |
        set -e

        # capture release tag.
        tag=$(echo "${{ inputs.tag-prefix }}${{ inputs.version }}" | xargs)

        # set output.
        echo "result=$tag" >>$GITHUB_OUTPUT
    - id: url
      shell: bash
      run: |
        set -e

        # capture full repository name.
        repository=$(echo "${{ inputs.owner }}/${{ inputs.repo }}" | xargs)

        # capture release url.
        url=${{ inputs.server }}/$repository/releases/tag/${{ steps.tag.outputs.result }}

        # set output.
        echo "result=$(echo "$url" | xargs)" >>$GITHUB_OUTPUT
branding:
  color: blue
  icon: link
